server:
  port: 8888

logging:
  level:
    root: info

spring:
  kafka:
    listener:
      concurrency: 12
    consumer:
      enable-auto-commit: false
      group-id: risk
      auto-offset-reset: latest
      bootstrap-servers: 10.173.245.211:9092,10.173.245.212:9092,10.173.245.213:9092,10.173.245.214:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  hbase:
    zookeeper:
      server-list: 10.174.25.117:2181,10.174.25.118:2181,10.174.25.119:2181,10.174.25.120:2181,10.174.25.121:2181
    service-table: service
    opcode-table: opcode
    ttl: 15552000

  datasource:
      url: jdbc:oracle:thin:@10.168.145.110:1521:logdb1
      username: ucr_log
      password: Ynyd!123

risk:
  threshold: 1.2
  serviceMin: 20
  opCodeMin: 20
  seperatorChar: '^'
  step: 10000
  needPause: false
  sleepmillis: 10
  redisAccumulator:
    threshold: 6

bean:
  service: 1
  opcode: 2


hubble:
  wadesearch:
    address: 10.174.59.28:10999,10.174.59.29:10999,10.174.60.28:10999,10.174.60.29:10999,127.0.0.1:10999